### ISSUE TITLE
Fix typographical errors in documentation's Background section

### ISSUE THREAD

**Issue by chiboycalix** [ajimae/colstonjs#2]
Typographical errors 
> - Bun is the lastest and arguably the fastest runtime environment for javascript, similar to node and deno. Bun uses JSC (JavaScriptCore) engine unlike node and deno which is the part of the reason why it's faster ~~then~~ than node and deno.

> - Bun supports ~90% of the native nodejs APIs including `fs`, `path` etc and also distribute it's packages ~~uses~~ using [npm](https://npmjs.com/) hence both yarn and npm are supported in bun.

**Comment by ajimae** [comment]
Fixed: https://github.com/ajimae/colstonjs/pull/3
